-- APIs for other addons
--
-- [BUGGED] DeathTimer.GetDeathTime([guid])
--
-- Return estimate death time (in seconds) for target or given guid; 
-- Return nil if estimate time <= 0 or data not available.
-- Recalculated once per 0.1s.
-- 